### ISSUE TITLE
Onboard Malvika

### ISSUE THREAD

**Issue by hlapp** [OBF/org#1]
* [x] Add to Board mailing list
* [x] Add to shared Google Drive
* [x] Add to Github organization
* [x] Add to Keybase team(s)
* [x] Add to calendar invite list for monthly Hangout 
* [x] Add to website editors
* [x] Update website

**Comment by hlapp** [comment]
Github pending acceptance from @malvikasharan. Keybase too.

**Comment by hlapp** [comment]
@cjfields can you add Malvika to the calendar invite for the monthly Hangout.

**Comment by cjfields** [comment]
@hlapp sure, I'll need an email but we probably shouldn't post it here.  Maybe we can correspond on the Board list or directly w/ @malvikasharan?

**Comment by hlapp** [comment]
@cjfields can you confirm that Malvika is on the invite for the monthly hangout. It seems that she is, but we should check it off here too so we can close this out.

@malvikasharan the only other open item is to add you to the website editors. With the change to WP I'm not sure anymore what this specifically entails, but it does seem you can edit the website? Could you and/or @yochannah confirm one way or the other?

**Comment by yochannah** [comment]
Malvika is a site editor according to the WP admin interface :)

**Comment by cjfields** [comment]
@hlapp @malvikasharan has been included in the last several meetings but we haven't set up a new scheduled meeting (had been waiting on the resolution for the Hangout/Zoom/etc meeting room).  

I'll go ahead and set up the perpetual invitation in my Google Calendar from Jan. on without the meeting room set (which we can change per meeting).  I'll also set up a tentative meeting for the public meeting Dec. 17, that would be best to use Zoom for dial-in.

**Comment by hlapp** [comment]
Thanks @cjfields. This is now the last remaining item. When done, can you check it off and close the issue?

**Comment by cjfields** [comment]
@hlapp Actually the meeting time is already set up (monthly on second Tuesday).  I have Jan. 14 and Feb 11 for the next one, w/ invitees:

* Me (chris)
* Hilmar
* Malvika
* Nomi
* Yo
* Bastian
* Peter
* Heather

I'll strip out the meeting link and resend the invitation, will close in a sec.

**Comment by malvikasharan** [comment]
Hello @cjfields and @hlapp, as @yochannah confirmed, I can edit the website :)

I will set a fresh Zoom link for the December public call and send the email to the board mailing list.

**Comment by cjfields** [comment]
@malvikasharan @hlapp just modified the calendar from Jan 2020 onwards to remove the old link, and also moved the Dec meeting to Dec 17.  Permissions have been opened up for others to edit as needed.
