### ISSUE TITLE
Public Board Meeting Dec 17, 2019

### ISSUE THREAD

**Issue by hlapp** [OBF/org#2]
## Date & time:

December 17, [16:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?msg=OBF+Public+Board+Meeting&iso=20191217T16&p1=1440&ah=1)

## Venue:

The meeting will be held over a phone conference call. Everyone is welcome to join the call. Dial-in information is below.

> Join FreeConference.com Meeting:
> https://hello.freeconference.com/conf/call/1024888
> 
> **One tap mobile:**
> +1 712-832-8330,,1024888#
> 
> **Dial-in using your phone:**
> United States: +1 712-832-8330 
> United States: +1 717-275-8940
> Canada: +1 867 292 3030 
> Ireland - Dublin: +353 1 437 0588 
> United Kingdom: +44 333 113 0100 
> Netherlands - Amsterdam: +31 20 262 1918 
> Finland - Helsinki: +358 9 74790416 
> Germany - Dusseldorf: +49 211 95987102 
> Australia - Pinjarra: +61 8 9520 3110 
> 
> **Access code:** 102 4888
> 
> Connection Test:
> https://hello.freeconference.com/system/test

### Old business

1. Approval ([#68](https://github.com/OBF/obf-docs/pull/68)) of [meeting minutes for July 2019 Public Meeting](https://github.com/OBF/obf-docs/blob/799a5e601ec2d7d78fe39265d3e83182d169afcd/minutes/2019-July.md) at BOSC 2019. 

### New business

1. Board elections. The terms of 5 Board members expire. All of them stand for re-election to the Board, though with some changes of officers:
    - Hilmar Lapp:  stepping down as President of the Board, running for At-Large seat.
    - Heather Wiencko: running for re-election, as Treasurer.
    - Peter Cock: running for re-election, as President of the Board.
    - Chris Fields: running for re-election, as Secretary.
    - Nomi Harris: running for re-election, as At-Large Board member. 
2. [Affiliated Project Status policy](https://github.com/OBF/obf-docs/pull/44). The public RfC period closed with no additional change requests or comments. The draft is ready for a vote to approve, adopt, and ratify, both for the Board, and for the OBF membership.
3. OBF-wide Code of Conduct policy: Status report
4. Financial reporting.
    - Status update on future mechanism
    - Change of fiscal year period

**Comment by peterjc** [comment]
This was easy on Chrome (had to allow JavaScript), may need to install something with Firefox.

**Comment by cjfields** [comment]
FreeConference worked quite well; I had to install the app for Safari but otherwise wasn't a problem.

**Comment by gedankenstuecke** [comment]
I had to skype in/use their landline numbers as the Chrome webpage said the call was full otherwise. 

--
Sent from a mobile device
mobile 🇪🇺: +49 176 213 044 66
mobile 🇺🇸: +1 510 944 4298

While I may be sending this email outside my normal office hours, I have no expectation to receive a reply outside yours

**Comment by nlharris** [comment]
Can this ticket be closed?

**Comment by cjfields** [comment]
Yes, the minutes have been merged.
